const POLYGON_LINE_WIDTH = 16;
const POLYGON_LINE_COLOR = 0x000000;
const POLYGON_MAX_EDGE_NUM = 11;
const POLYGON_MAX_VERTICE_VALUE = 20;
const POLYGON_MIN_VERTICE_VALUE = -20;
const POLYGON_RADIUS = 170;
